"use client";

import { useEffect, useState, type FormEvent } from "react";
import { MonthlyDashboard } from "@/components/dashboard/monthly-dashboard";
import { createClient } from "@/lib/supabase/client";
import type { Card, Concept, Expense, ExpenseWithRelations, Subscription } from "@/types/database";

type View = "dashboard" | "cards" | "concepts" | "subscriptions" | "expenses";
const today = () => new Date().toISOString().slice(0, 10);

export function FinanceManager() {
  const [view, setView] = useState<View>("dashboard"); const [userId, setUserId] = useState("");
  const [cards, setCards] = useState<Card[]>([]); const [concepts, setConcepts] = useState<Concept[]>([]); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [error, setError] = useState("");
  const [editing, setEditing] = useState<{ table: "cards" | "concepts" | "subscriptions" | "expenses"; id: string; name: string } | null>(null);
  const supabase = createClient();
  async function refresh() {
    const [{ data: cardRows }, { data: conceptRows }, { data: subscriptionRows }, { data: expenseRows }] = await Promise.all([supabase.from("cards").select("*").order("name"), supabase.from("concepts").select("*").order("name"), supabase.from("subscriptions").select("*").order("next_charge_date"), supabase.from("expenses").select("*").order("expense_date", { ascending: false })]);
    setCards((cardRows ?? []) as Card[]); setConcepts((conceptRows ?? []) as Concept[]); setSubscriptions((subscriptionRows ?? []) as Subscription[]); setExpenses((expenseRows ?? []) as Expense[]);
  }
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (data.user) { setUserId(data.user.id); refresh(); } }); }, []);
  async function save(table: "cards" | "concepts" | "subscriptions" | "expenses", values: Record<string, unknown>, form: HTMLFormElement) {
    setError(""); const { error: saveError } = await supabase.from(table).insert({ ...values, user_id: userId });
    if (saveError) setError(saveError.message); else { form.reset(); await refresh(); }
  }
  async function remove(table: "cards" | "concepts" | "subscriptions" | "expenses", id: string) {
    if (!confirm("¿Eliminar este registro?")) return; const { error: deleteError } = await supabase.from(table).delete().eq("id", id); if (deleteError) setError(deleteError.message); else await refresh();
  }
  async function rename(name: string) {
    if (!editing || !name.trim()) return;
    const { error: updateError } = await supabase.from(editing.table).update({ name: name.trim() }).eq("id", editing.id);
    if (updateError) setError(updateError.message); else { setEditing(null); await refresh(); }
  }
  async function signOut() { await supabase.auth.signOut(); location.assign("/login"); }
  const enrichedExpenses: ExpenseWithRelations[] = expenses.map((expense) => ({ ...expense, card: cards.find((card) => card.id === expense.card_id) ?? null, concept: concepts.find((concept) => concept.id === expense.concept_id) ?? null }));
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-7 sm:px-8"><header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-emerald-400">Control personal</p><h1 className="text-2xl font-bold text-slate-100">Mis gastos</h1></div><button onClick={signOut} className="text-sm text-slate-400 hover:text-slate-100">Cerrar sesión</button></header><nav className="mb-6 flex flex-wrap gap-2">{([['dashboard','Resumen'],['cards','Tarjetas'],['concepts','Conceptos'],['subscriptions','Suscripciones'],['expenses','Gastos']] as [View, string][]).map(([key, label]) => <button key={key} onClick={() => setView(key)} className={`rounded-lg px-3 py-2 text-sm font-medium ${view === key ? "bg-emerald-500 text-slate-950" : "bg-slate-900 text-slate-300 hover:bg-slate-800"}`}>{label}</button>)}</nav>{error && <p className="mb-4 rounded-lg border border-red-900 bg-red-950/50 p-3 text-sm text-red-300">{error}</p>}{view === "dashboard" && <MonthlyDashboard expenses={enrichedExpenses} subscriptions={subscriptions} />}{view === "cards" && <Cards cards={cards} onSave={(v, f) => save("cards", v, f)} onRemove={(id) => remove("cards", id)} onRename={(id, name) => setEditing({ table: "cards", id, name })} />}{view === "concepts" && <Concepts concepts={concepts} onSave={(v, f) => save("concepts", v, f)} onRemove={(id) => remove("concepts", id)} onRename={(id, name) => setEditing({ table: "concepts", id, name })} />}{view === "subscriptions" && <Subscriptions cards={cards} concepts={concepts} subscriptions={subscriptions} onSave={(v, f) => save("subscriptions", v, f)} onRemove={(id) => remove("subscriptions", id)} onRename={(id, name) => setEditing({ table: "subscriptions", id, name })} />}{view === "expenses" && <Expenses cards={cards} concepts={concepts} expenses={expenses} onSave={(v, f) => save("expenses", v, f)} onRemove={(id) => remove("expenses", id)} onRename={(id, name) => setEditing({ table: "expenses", id, name })} />}{editing && <EditNameModal initialName={editing.name} onClose={() => setEditing(null)} onSave={rename} />}</main>;
}

type Save = (values: Record<string, unknown>, form: HTMLFormElement) => Promise<void>;
function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="mb-4 font-semibold text-slate-100">{title}</h2>{children}</section>; }
function List({ children }: { children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><ul className="divide-y divide-slate-800">{children}</ul></section>; }
const Input = ({ name, ...props }: React.InputHTMLAttributes<HTMLInputElement>) => <input name={name} {...props} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100 outline-none focus:border-emerald-500" />;
const Select = ({ name, children }: { name: string; children: React.ReactNode }) => <select name={name} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100 outline-none focus:border-emerald-500">{children}</select>;
function Actions({ onRemove, onRename }: { onRemove: () => void; onRename: () => void }) { return <span className="flex gap-3"><button onClick={onRename} className="text-sm text-emerald-400 hover:text-emerald-300">Editar</button><button onClick={onRemove} className="text-sm text-red-400 hover:text-red-300">Eliminar</button></span>; }
function EditNameModal({ initialName, onClose, onSave }: { initialName: string; onClose: () => void; onSave: (name: string) => Promise<void> }) { const [name, setName] = useState(initialName); const [saving, setSaving] = useState(false); return <div role="dialog" aria-modal="true" aria-label="Editar registro" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 px-5"><form onSubmit={async (event) => { event.preventDefault(); setSaving(true); await onSave(name); setSaving(false); }} className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><h2 className="text-lg font-semibold text-slate-100">Editar nombre</h2><p className="mt-1 text-sm text-slate-400">Actualiza el nombre del registro.</p><Input autoFocus required name="edit-name" value={name} onChange={(event) => setName(event.target.value)} className="mt-5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100 outline-none focus:border-emerald-500" /><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg px-4 py-2 text-sm font-medium text-slate-300 hover:bg-slate-800">Cancelar</button><button disabled={saving} className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-60">{saving ? "Guardando…" : "Guardar cambios"}</button></div></form></div>; }

function Cards({ cards, onSave, onRemove, onRename }: { cards: Card[]; onSave: Save; onRemove: (id: string) => void; onRename: (id: string, name: string) => void }) { return <><FormCard title="Nueva tarjeta"><form className="grid gap-3 sm:grid-cols-3" onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ name: f.get("name"), bank_name: f.get("bank_name") || null, type: f.get("type"), last_four: f.get("last_four") || null, credit_limit: f.get("credit_limit") ? Number(f.get("credit_limit")) : null, cutoff_day: f.get("cutoff_day") ? Number(f.get("cutoff_day")) : null, payment_due_day: f.get("payment_due_day") ? Number(f.get("payment_due_day")) : null }, e.currentTarget); }}><Input required name="name" placeholder="Nombre" /><Input name="bank_name" placeholder="Banco" /><Select name="type"><option value="credit">Crédito</option><option value="debit">Débito</option></Select><Input name="last_four" maxLength={4} inputMode="numeric" placeholder="Últimos 4 dígitos" /><Input name="credit_limit" type="number" min="0" step="0.01" placeholder="Límite" /><Input name="cutoff_day" type="number" min="1" max="31" placeholder="Día de corte" /><Input name="payment_due_day" type="number" min="1" max="31" placeholder="Día de pago" /><button className="rounded-lg bg-emerald-500 px-4 py-2 font-semibold text-slate-950">Guardar</button></form></FormCard><List>{cards.map((card) => <li key={card.id} className="flex justify-between gap-4 p-4 text-slate-200"><div><p className="font-medium">{card.name}</p><p className="text-sm text-slate-400">{card.bank_name ?? "Sin banco"} · {card.type === "credit" ? "Crédito" : "Débito"}</p></div><Actions onRename={() => onRename(card.id, card.name)} onRemove={() => onRemove(card.id)} /></li>)}</List></>; }
function Concepts({ concepts, onSave, onRemove, onRename }: { concepts: Concept[]; onSave: Save; onRemove: (id: string) => void; onRename: (id: string, name: string) => void }) { return <><FormCard title="Nuevo concepto"><form className="flex gap-3" onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ name: f.get("name"), color: f.get("color") || null }, e.currentTarget); }}><Input required name="name" placeholder="Ej. Comida" /><Input name="color" type="color" className="h-10 w-14 rounded-lg border border-slate-700 bg-slate-950 p-1" /><button className="rounded-lg bg-emerald-500 px-4 py-2 font-semibold text-slate-950">Guardar</button></form></FormCard><List>{concepts.map((concept) => <li key={concept.id} className="flex justify-between p-4 text-slate-200"><span><i className="mr-2 inline-block size-3 rounded-full" style={{ background: concept.color ?? "#64748b" }} />{concept.name}</span><Actions onRename={() => onRename(concept.id, concept.name)} onRemove={() => onRemove(concept.id)} /></li>)}</List></>; }

function Subscriptions({ cards, concepts, subscriptions, onSave, onRemove, onRename }: { cards: Card[]; concepts: Concept[]; subscriptions: Subscription[]; onSave: Save; onRemove: (id: string) => void; onRename: (id: string, name: string) => void }) { return <><FormCard title="Nueva suscripción"><form className="grid gap-3 sm:grid-cols-3" onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ name: f.get("name"), amount: Number(f.get("amount")), card_id: f.get("card_id"), concept_id: f.get("concept_id") || null, cycle: f.get("cycle"), billing_day: f.get("billing_day") ? Number(f.get("billing_day")) : null, start_date: f.get("start_date"), end_date: f.get("end_date") || null }, e.currentTarget); }}><Input required name="name" placeholder="Ej. Netflix" /><Input required name="amount" type="number" min="0.01" step="0.01" placeholder="Monto" /><Select name="card_id">{cards.map((card) => <option key={card.id} value={card.id}>{card.name}</option>)}</Select><Select name="concept_id"><option value="">Sin concepto</option>{concepts.map((concept) => <option key={concept.id} value={concept.id}>{concept.name}</option>)}</Select><Select name="cycle"><option value="monthly">Mensual</option><option value="yearly">Anual</option><option value="weekly">Semanal</option></Select><Input name="billing_day" type="number" min="1" max="31" placeholder="Día de cobro" /><Input required name="start_date" type="date" defaultValue={today()} /><Input name="end_date" type="date" placeholder="Fecha límite opcional" /><button disabled={!cards.length} className="rounded-lg bg-emerald-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">Guardar</button></form>{!cards.length && <p className="mt-3 text-sm text-amber-300">Crea una tarjeta antes de agregar suscripciones.</p>}</FormCard><List>{subscriptions.map((subscription) => <li key={subscription.id} className="flex justify-between gap-4 p-4 text-slate-200"><div><p className="font-medium">{subscription.name} · ${Number(subscription.amount).toFixed(2)}</p><p className="text-sm text-slate-400">{subscription.cycle} · {subscription.end_date ? `Termina: ${subscription.end_date}` : "Sin fecha límite"}</p></div><Actions onRename={() => onRename(subscription.id, subscription.name)} onRemove={() => onRemove(subscription.id)} /></li>)}</List></>; }

function Expenses({ cards, concepts, expenses, onSave, onRemove, onRename }: { cards: Card[]; concepts: Concept[]; expenses: Expense[]; onSave: Save; onRemove: (id: string) => void; onRename: (id: string, name: string) => void }) { return <><FormCard title="Registrar gasto"><form className="grid gap-3 sm:grid-cols-3" onSubmit={(e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const kind = String(f.get("kind")); onSave({ name: f.get("name"), amount: Number(f.get("amount")), expense_date: f.get("expense_date"), card_id: f.get("card_id") || null, concept_id: f.get("concept_id") || null, kind, recurrence_cycle: kind === "recurring" ? f.get("recurrence_cycle") : null, recurrence_end_date: kind === "recurring" ? f.get("recurrence_end_date") || null : null }, e.currentTarget); }}><Input required name="name" placeholder="Descripción" /><Input required name="amount" type="number" min="0.01" step="0.01" placeholder="Monto" /><Input required name="expense_date" type="date" defaultValue={today()} /><Select name="card_id"><option value="">Sin tarjeta</option>{cards.map((card) => <option key={card.id} value={card.id}>{card.name}</option>)}</Select><Select name="concept_id"><option value="">Sin concepto</option>{concepts.map((concept) => <option key={concept.id} value={concept.id}>{concept.name}</option>)}</Select><Select name="kind"><option value="one_time">Único</option><option value="recurring">Recurrente</option></Select><Select name="recurrence_cycle"><option value="monthly">Ciclo mensual</option><option value="weekly">Ciclo semanal</option><option value="yearly">Ciclo anual</option></Select><Input name="recurrence_end_date" type="date" placeholder="Fecha límite opcional" /><button className="rounded-lg bg-emerald-500 px-4 py-2 font-semibold text-slate-950">Guardar</button></form></FormCard><List>{expenses.map((expense) => <li key={expense.id} className="flex justify-between gap-4 p-4 text-slate-200"><div><p className="font-medium">{expense.name} · ${Number(expense.amount).toFixed(2)}</p><p className="text-sm text-slate-400">{expense.expense_date} · {expense.kind === "recurring" ? expense.recurrence_end_date ? `Recurrente hasta ${expense.recurrence_end_date}` : "Recurrente sin límite" : "Único"}</p></div><Actions onRename={() => onRename(expense.id, expense.name)} onRemove={() => onRemove(expense.id)} /></li>)}</List></>; }
